builds:
  - binary: gcp-builder
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}}

archive:
  format: tar.gz
  replacements:
    amd64: x86_64
    darwin: darwin
  files:
    - README.md
